# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/study/FPGA/study_project/shop/prj/shop/shop.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
# IP: The module: 'blk_mem_gen_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/study/FPGA/study_project/shop/prj/shop/shop.gen/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/study/FPGA/study_project/shop/prj/shop/shop.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
# IP: The module: 'blk_mem_gen_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/study/FPGA/study_project/shop/prj/shop/shop.gen/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
